# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/apps/poker/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/apps/poker/00_card.ipynb 3
suits = ["C","D","H","S"]
ranks = [None, "A"] + [str(n) for n in range(2,11)] + ["J","Q","K"]

# %% ../nbs/apps/poker/00_card.ipynb 10
class Card:
    "Represents a standard playing card."
    def __init__(self,
                 suit:int=0,  # an index into suits
                 rank:int=0): # an index into ranks
        self.suit = suit
        self.rank = rank 

    def __str__(self):
        return f'{ranks[self.rank]}{suits[self.suit]}'
    
    def __eq__(self, other):
        return (self.suit == other.suit and self.rank == other.rank)
    
    def __lt__(self, other):
        return self.rank < other.rank  
    
    def __gt__(self, other):
        return self.rank > other.rank

    def __hash__(self):
        return hash((self.suit, self.rank))

    def __add__(self, other):
        return self.rank + other.rank

    def __radd__(self, other):
        return self.rank + other

    def __sub__(self, other):
        return self.rank - other.rank

    def __rsub__(self, other):
        return other.rank - self.rank
